1

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
a=arr.copy()
arr[3]=9
print(arr)
print(a)

[1 2 3 9 5 6]
[1 2 3 4 5 6]


2

In [ ]:
import numpy as np
arr=np.array([1,5,4,6,4])
a=arr.view()
arr[2]=8
print(arr)
print(a)

[1 5 8 6 4]
[1 5 8 6 4]


3

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
a=arr.copy()
arr[3]=9
print(arr)
print(a)
print(a.base)
print()
import numpy as np
arr=np.array([1,5,4,6,4])
a=arr.view()
arr[2]=8
print(arr)
print(a)
print(a.base)



[1 2 3 9 5 6]
[1 2 3 4 5 6]
None

[1 5 8 6 4]
[1 5 8 6 4]
[1 5 8 6 4]


4

In [ ]:
import numpy as np
a=np.array([[1,2],[6,7]])
b=a[0].view()
b[1]=5
print(a)
print(b)

[[1 5]
 [6 7]]
[1 5]


5

In [3]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=a[0]
print(b)
print("-------------------------------")
print(b.base)

[1 2]
-------------------------------
[[1 2]
 [3 4]]


6